model_type: linmult
input_modality_channels:
  - 41
  - 256
  - 25
  - 1024
  - 768
output_dim:
  - 8
  - 3
d_model: 40
n_heads: 6
n_layers: 4
dropout_embedding: 0.
dropout_ca: 0.1
dropout_sa: 0.1
dropout_relu: 0.1
dropout_residual: 0.1
dropout_output: 0
time_reduce_type: gap
add_ffn_fusion: True
attention_type: linear