# experiment
output_dir: results/STL/sentiment
seed: 42

accelerator: gpu
devices:
  - 0
float32_matmul_precision: medium # high, highest

tasks:
  sentiment: # [-3, +3]
    weight: 1.0
    loss_fn: bell_l2_l1_loss
    metrics:
      - ACC_7
      - ACC_2
      - F1_7
      - F1_2
      - MAE
      - CORR
  sentiment_class:
    num_classes: 3
    weight: 1.0
    loss_fn: cross_entropy
    metrics:
      - ACC
      - P
      - R
      - F1

consistency_rules:
  - name: sentiment
    weight: 0.1

n_epochs: 100
warmup_epochs: 5

optimizer:
  name: adamw
  base_lr: 0.001

lr_scheduler:
  name: CosineAnnealingLR

early_stopping:
  monitor: valid_loss
  patience: 20
  mode: min

checkpoints:
  - name: checkpoint_valid_loss
    monitor: valid_loss
    mode: min
  - name: checkpoint_valid_sentiment_MAE
    monitor: valid_sentiment_MAE
    mode: min
  - name: checkpoint_valid_sentiment_F1_2
    monitor: valid_sentiment_F1_2
    mode: max
  - name: checkpoint_valid_sentiment_class_F1
    monitor: valid_sentiment_class_F1
    mode: max