train_db:
  - ravdess
valid_db:
  - ravdess
test_db:
  - ravdess

feature_list:
  - wavlm_baseplus
  - clip

ravdess_split: random
ravdess_speech_only: True
ravdess_modality: av

batch_size: 32
time_dim_egemaps: 1000
time_dim_wavlm: 500
time_dim_frames: 300

num_workers: 3
seed: 42