train_db:
  - afewva
  - ravdess
valid_db:
  - afewva
  - ravdess
test_db:
  - afewva
  - ravdess

feature_list:
  - egemaps_lld
  - wavlm_baseplus
  - opengraphau
  - fabnet
  - clip

ravdess_split: random
ravdess_speech_only: True

batch_size: 8
time_dim_egemaps: 1000
time_dim_wavlm: 500
time_dim_frames: 300

num_workers: 3
seed: 42