accelerator: gpu
devices:
- 0
float32_matmul_precision: medium # high, highest

tasks:
  emotion_class:
    type: classification
    num_classes: 8
    loss_fn: cross_entropy
    metrics: ["ACC", "F1"]
  emotion_intensity:
    type: classification
    num_classes: 2
    loss_fn: cross_entropy
    metrics: ["ACC", "F1"]

datasets:
  ravdess:
    tasks: ["emotion_class", "emotion_intensity"]

n_epochs: 100
shake: False

optimizer:
  name: radam
  base_lr: 0.01
  weight_decay: 1e-6
  decoupled_weight_decay: True

lr_scheduler:
  name: cosine_warmup
  warmup_steps: 0.05 # 5%

output_dir: results/unimodal/ravdess_egemaps_lld