accelerator: gpu
devices:
- 0
float32_matmul_precision: medium # high, highest

tasks:
  emotion_class:
    type: classification
    num_classes: 8
    metrics: ["ACC", "F1"]
  emotion_intensity:
    type: classification
    num_classes: 2
    metrics: ["ACC", "F1"]
  valence_arousal:
    type: regression
    metrics: ["RMSE", "PCC", "CCC"]

datasets:
  ravdess:
    tasks: ["emotion_class", "emotion_intensity"]
  afew_va:
    tasks: ["valence_arousal"]

n_epochs: 20
shake: False

optimizer:
  name: adamw # only this one is supported now
  base_lr: 0.001
  weight_decay: 1e-5

lr_scheduler:
  name: CosineAnnealingLR # only this one is supported now
  T_max: 20 # n_epochs

output_dir: training_results/