db_processed: "data/db_processed/MEAD"
batch_size: 256
window_size_sec: 7.5
feature_list:
  - "egemaps_functionals"
train_ids:
  - "M003"
  - "M005"
  - "M007"
  - "M009"
  - "M011"
  - "M012"
  - "M013"
  - "M019"
  - "M022"
  - "M023"
  - "M024"
  - "M025"
  - "M026"
  - "M027"
  - "M028"
  - "M029"
  - "M030"
  - "M031"
  - "M032"
  - "W009"
  - "W011"
  - "W014"
  - "W015"
  - "W016"
  - "W017"
  - "W018"
  - "W019"
  - "W021"
  - "W023"
  - "W024"
  - "W025"
  - "W026"
valid_ids:
  - "M033"
  - "M034"
  - "M035"
  - "M037"
  - "W028"
  - "W029"
  - "W033"
  - "W035"
test_ids:
  - "M039"
  - "M040"
  - "M041"
  - "M042"
  - "W036"
  - "W037"
  - "W038"
  - "W040"