base_save_dir: data/logs
loss_fn: ce
optimizer: sgd # "adam", "adamw", "radam", "sgd"
learning_rate: 0.003
weight_decay: 0.000001
lr_scheduler: reducelronplateau # "cosine_warmup", "reducelronplateau", "warm_restart"
max_epochs: 20
patience: 20
num_io_workers: 4
seed: 42