# experiment
output_dir: results/poster/MDMTL/stage1
seed: 42

accelerator: gpu
strategy: auto
devices:
  - 0
float32_matmul_precision: medium # high, highest

tasks:
  tmm_wavlm_baseplus:
    weight: 1.0
    loss_fn: mse
    metrics:
      - MSE
  tmm_clip:
    weight: 1.0
    loss_fn: mse
    metrics:
      - MSE

n_epochs: 75
warmup_epochs: 5

optimizer:
  name: adamw
  base_lr: 0.001
  weight_decay: 0.00001

awl:
  lr: 0.01

lr_scheduler:
  name: CosineAnnealingWarmRestarts

#early_stopping:
#  monitor: valid_loss
#  patience: 30
#  mode: min

checkpoints:
  - name: checkpoint_valid_loss
    monitor: valid_loss
    mode: min

stage: tmm_pretraining
